# charging session simulieren 
## 1-Random Werte Erstellung

In [46]:
import random
from datetime import datetime, timedelta

battery_start = random.randint(10, 40)
battery_end = random.randint(60, 95)

print(f"Battery Start: {battery_start}%")
print(f"Battery End:   {battery_end}%")

Battery Start: 39%
Battery End:   65%

## 2-Eine komplette Session

In [47]:
import random
from datetime import datetime, timedelta

battery_capacity = 75  # kWh — Tesla Model 

battery_start = random.randint(10, 40)
battery_end   = random.randint(battery_start + 20, 95)
energy_kwh = (battery_capacity * (battery_end - battery_start)) / 100

print(f"Battery Start: {battery_start}%")
print(f"Battery End:   {battery_end}%")
print(f"Energy:        {energy_kwh} kWh")

Battery Start: 12%
Battery End:   63%
Energy:        38.25 kWh

## 3-Ladedauer berechnen (in Minuten)

In [48]:
power_kw = 50  # Ladegeschwindigkeit
duration_hours = energy_kwh / power_kw
duration_minutes = duration_hours * 60

print(f"Duration: {round(duration_minutes)} Minuten")

Duration: 46 Minuten

## 4-Start Zeit

In [49]:
start_time = datetime.now().replace(microsecond=0)
end_time = start_time + timedelta(minutes=duration_minutes)

print(f"Start: {start_time}")
print(f"End:   {end_time}")

Start: 2026-05-10 23:47:10
End:   2026-05-11 00:33:04

## 5- Eine Session als Dictionary

In [50]:
import json

session = {
    "vehicle_id":        "EV_001",
    "battery_start_pct": battery_start,
    "battery_end_pct":   battery_end,
    "energy_kwh":        energy_kwh,
    "duration_minutes":  round(duration_minutes),
    "start_time":        start_time,
    "end_time":          end_time,
    "power_kw":          power_kw
}

print(json.dumps(session, indent=2, default=str)) # default=str → weil datetime kein JSON Format ist

{
  "vehicle_id": "EV_001",
  "battery_start_pct": 12,
  "battery_end_pct": 63,
  "energy_kwh": 38.25,
  "duration_minutes": 46,
  "start_time": "2026-05-10 23:47:10",
  "end_time": "2026-05-11 00:33:04",
  "power_kw": 50
}

## 6- 100 Sessions simulieren

In [51]:
sessions = []

for i in range(100):
   
    battery_start = random.randint(10, 40)
    battery_end = random.randint(battery_start + 20, 95)
    energy_kwh = (75 * (battery_end - battery_start)) / 100
    duration_minutes = round((energy_kwh / 50) * 60)
    start_time = datetime.now().replace(microsecond=0)
    end_time = start_time + timedelta(minutes=duration_minutes)

    session = {
        "vehicle_id": f"EV_{i+1:03d}",  # EV_001, EV_002...
        "battery_start_pct": battery_start,
        "battery_end_pct": battery_end,
        "energy_kwh": energy_kwh,
        "duration_minutes": duration_minutes,
        "start_time": start_time,
        "end_time": end_time,
        "power_kw": 50
    }

    sessions.append(session)

print(f"Total sessions: {len(sessions)}")
print(sessions[0])
print(sessions[1])

Total sessions: 100
{'vehicle_id': 'EV_001', 'battery_start_pct': 32, 'battery_end_pct': 63, 'energy_kwh': 23.25, 'duration_minutes': 28, 'start_time': datetime.datetime(2026, 5, 10, 23, 47, 10), 'end_time': datetime.datetime(2026, 5, 11, 0, 15, 10), 'power_kw': 50}
{'vehicle_id': 'EV_002', 'battery_start_pct': 21, 'battery_end_pct': 66, 'energy_kwh': 33.75, 'duration_minutes': 40, 'start_time': datetime.datetime(2026, 5, 10, 23, 47, 10), 'end_time': datetime.datetime(2026, 5, 11, 0, 27, 10), 'power_kw': 50}

## 7- DataFrame erstellen

In [52]:
import pandas as pd 

df = pd.DataFrame(sessions)

display(df.head())

df.info()

#alle Start datum sind gleich

,vehicle_id,battery_start_pct,battery_end_pct,energy_kwh,duration_minutes,start_time,end_time,power_kw
0,EV_001,32,63,23.25,28,2026-05-10 23:47:10,2026-05-11 00:15:10,50
1,EV_002,21,66,33.75,40,2026-05-10 23:47:10,2026-05-11 00:27:10,50
2,EV_003,20,79,44.25,53,2026-05-10 23:47:10,2026-05-11 00:40:10,50
3,EV_004,16,76,45.00,54,2026-05-10 23:47:10,2026-05-11 00:41:10,50
4,EV_005,17,80,47.25,57,2026-05-10 23:47:10,2026-05-11 00:44:10,50

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   vehicle_id         100 non-null    str
 1   battery_start_pct  100 non-null    int64
 2   battery_end_pct    100 non-null    int64
 3   energy_kwh         100 non-null    float64
 4   duration_minutes   100 non-null    int64
 5   start_time         100 non-null    datetime64[us]
 6   end_time           100 non-null    datetime64[us]
 7   power_kw           100 non-null    int64
dtypes: datetime64[us](2), float64(1), int64(4), str(1)
memory usage: 6.4 KB

## 8- Start datum behandeln und station stadt Hinzufügen

In [56]:
sessions = []

for i in range(100):
    # اختار محطة عشوائية
    station = random.choice(stations)
    
    battery_start = random.randint(10, 40)
    battery_end = random.randint(battery_start + 20, 95)
    energy_kwh = (75 * (battery_end - battery_start)) / 100
    duration_minutes = round((energy_kwh / station["power_kw"]) * 60)
    
    start_time = datetime.now().replace(microsecond=0) - timedelta(
        days=random.randint(0, 30),
        hours=random.randint(0, 23),
        minutes=random.randint(0, 59)
    )
    end_time = start_time + timedelta(minutes=duration_minutes)

    session = {
        "vehicle_id":        f"EV_{i+1:03d}",
        "station_id":        station["station_id"],
        "city":              station["city"],
        "power_kw":          station["power_kw"],
        "battery_start_pct": battery_start,
        "battery_end_pct":   battery_end,
        "energy_kwh":        energy_kwh,
        "duration_minutes":  duration_minutes,
        "start_time":        start_time,
        "end_time":          end_time,
    }
    sessions.append(session)
df = pd.DataFrame(sessions)

display(df.head())

,vehicle_id,station_id,city,power_kw,battery_start_pct,battery_end_pct,energy_kwh,duration_minutes,start_time,end_time
0,EV_001,487810,Berlin,50,24,60,27.00,32,2026-04-23 13:44:47,2026-04-23 14:16:47
1,EV_002,487810,Berlin,50,33,95,46.50,56,2026-04-24 23:54:47,2026-04-25 00:50:47
2,EV_003,487812,Aschersleben,300,17,65,36.00,7,2026-04-24 16:49:47,2026-04-24 16:56:47
3,EV_004,487810,Berlin,50,17,42,18.75,22,2026-04-28 12:41:47,2026-04-28 13:03:47
4,EV_005,487812,Aschersleben,300,11,87,57.00,11,2026-04-29 20:20:47,2026-04-29 20:31:47